openapi: 3.2.0
info:
  title: Asset Management Asset Upload Batches API
  description: This is the Asset Management Rest API Documentation
  contact:
    name: CAMS Team
  version: 1.0.0
servers:
- url: https://api.everbridge.net/rest/v2/asset-management
tags:
- name: Asset Upload Batches
  description: Asset upload batch management operations
paths:
  /asset-upload-batches:
    get:
      tags:
      - Asset Upload Batches
      operationId: EBS AM List Upload Assets Batches
      summary: List Upload Assets Batches
      description: Retrieve all upload assets batches for a given asset type with in an organization.
      parameters:
      - description: The organization ID
        in: header
        name: X-EB-Organization-Id
        required: true
        schema:
          $ref: '#/components/schemas/organizationId'
      - description: The page number of assets to return.
        in: query
        name: pageNumber
        required: false
        schema:
          type: integer
          default: '1'
      - description: The page size of assets to return.
        in: query
        name: pageSize
        required: false
        schema:
          type: integer
      - description: Sort uploads by field names
        in: query
        name: sort
        required: false
        schema:
          type: string
          default: -createdTimestamp
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListUploadBatchResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    pageSize: 100
                    start: 0
                    totalCount: 13
                    data:
                    - id: 68076691610b4b5869d240a5
                      organizationId: 1536984111644674
                      createdId: 1530249602924608
                      createdName: Nandish Siddaiah
                      lastModifiedId: 1530249602924608
                      lastModifiedName: Nandish Siddaiah
                      createdTimestamp: 1745315473046
                      lastModifiedTimestamp: 1745316126070
                      originalFileName: For API Gateway___91ae67a7-4390-455b-b505-858333558edd.csv
                      fileSuffix: .csv
                      storedFilePath: 1536984111644674/68076691610b4b5869d240a5/68076691610b4b5869d240a5.csv
                      fileSize: 918
                      contentType: text/csv
                      type: ASSET
                      uploadStatus: GEOCODING
                      uploadType: UPDATE
                      source: API
                      assetTypeId: 665ff8e1a1b61d39e577b9c6
                      assetTypeName: Buildings
                      totalRecordNum: 5
                      successNum: 5
                      withErrorNum: 0
                      criticalNum: 0
                      geocodingSuccessNum: 0
                      geocodingFailureNum: 0
                      geocodingTotalNum: 0
                      csvDelimiter: COMMA
                    - id: 6807668a610b4b5869d240a4
                      organizationId: 1536984111644674
                      createdId: 1530249602924608
                      createdName: Nandish Siddaiah
                      lastModifiedId: 1530249602924608
                      lastModifiedName: Nandish Siddaiah
                      createdTimestamp: 1745315466195
                      lastModifiedTimestamp: 1745316126065
                      originalFileName: For API Gateway___91ae67a7-4390-455b-b505-858333558edd.csv
                      fileSuffix: .csv
                      storedFilePath: 1536984111644674/6807668a610b4b5869d240a4/6807668a610b4b5869d240a4.csv
                      fileSize: 918
                      contentType: text/csv
                      type: ASSET
                      uploadStatus: GEOCODING
                      uploadType: UPDATE
                      source: API
                      assetTypeId: 665856825d59930bc2151633
                      assetTypeName: For API Gateway
                      totalRecordNum: 5
                      successNum: 5
                      withErrorNum: 0
                      criticalNum: 0
                      geocodingSuccessNum: 0
                      geocodingFailureNum: 0
                      geocodingTotalNum: 0
                      csvDelimiter: COMMA
                    currentPageNo: 1
                    totalPageCount: 1
          description: OK
        '400':
          content:
            text/plain:
              schema:
                oneOf:
                - type: string
                - type: object
              examples:
                Invalid Org ID:
                  summary: Invalid Org ID
                  value: 'BadRequest due to Not Found DataCenterId, orgId: 15369841116446741'
          description: Invalid Org ID
        '401':
          content:
            application/json:
              schema: {}
              examples:
                No X-EB-Organization-Id Header:
                  summary: Missing X-EB-Organization-Id Header
                  value: {}
          description: Missing X-EB-Organization-Id Header
      security:
      - API_Authorizer: []
      - BasicAuth: []
      - api_key: []
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: GET
        uri: https://ebs-restapi-prod-us.evbg.io/rest/v2/asset-management/asset-upload-batches
        responses:
          default:
            statusCode: '200'
        requestParameters:
          integration.request.header.Authorization: context.authorizer.override_token
        passthroughBehavior: when_no_match
    post:
      tags:
      - Asset Upload Batches
      operationId: EBS AM Upload Asset Batches
      summary: Upload Asset Batches
      description: Upload assets batches to an organization.
      parameters:
      - description: The organization ID
        in: header
        name: X-EB-Organization-Id
        required: true
        schema:
          $ref: '#/components/schemas/organizationId'
      - description: Source protocol type. Can be of API, SFTP or WEB
        in: query
        name: source
        required: true
        schema:
          type: string
          enum:
          - API
          - SFTP
          - WEB
          default: API
      - description: Upload action type. Can be one of UPDATE, REPLACE or DELETE
        in: query
        name: uploadType
        required: true
        schema:
          type: string
          enum:
          - UPDATE
          - REPLACE
          - DELETE
          default: UPDATE
      - description: Name of Asset Type
        in: query
        name: assetTypeName
        required: true
        schema:
          type: string
      - description: Available on manager portal (Settings --> Organization --> Contacts/Assets --> Assert Types)
        in: query
        name: assetTypeId
        required: false
        schema:
          type: string
          example: 665ff8e1a1b61d39e577b9c6
          default: 665ff8e1a1b61d39e577b9c6
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
              - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadBatchAssetResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    id: 68076691610b4b5869d240a5
                    organizationId: 1536984111644674
                    createdId: 1530249602924608
                    createdName: Nandish Siddaiah
                    lastModifiedId: 1530249602924608
                    lastModifiedName: Nandish Siddaiah
                    createdTimestamp: 1745315473046
                    lastModifiedTimestamp: 1745315473137
                    originalFileName: For API Gateway___91ae67a7-4390-455b-b505-858333558edd.csv
                    fileSuffix: .csv
                    storedFilePath: 1536984111644674/68076691610b4b5869d240a5/68076691610b4b5869d240a5.csv
                    fileSize: 918
                    contentType: text/csv
                    type: ASSET
                    uploadStatus: PENDING
                    uploadType: UPDATE
                    source: API
                    assetTypeId: 665ff8e1a1b61d39e577b9c6
                    assetTypeName: Buildings
                    totalRecordNum: 0
                    successNum: 0
                    withErrorNum: 0
                    criticalNum: 0
                    geocodingSuccessNum: 0
                    geocodingFailureNum: 0
                    geocodingTotalNum: 0
                    csvDelimiter: COMMA
        '400':
          content:
            text/plain:
              schema:
                oneOf:
                - type: string
                - type: object
              examples:
                Invalid Org ID:
                  summary: Invalid Org ID
                  value: 'BadRequest due to Not Found DataCenterId, orgId: 15369841116446741'
          description: Invalid Org ID
        '401':
          content:
            application/json:
              schema: {}
              examples:
                No X-EB-Organization-Id Header:
                  summary: Missing X-EB-Organization-Id Header
                  value: {}
          description: Missing X-EB-Organization-Id Header
      security:
      - API_Authorizer: []
      - BasicAuth: []
      - api_key: []
      x-amazon-apigateway-integration:
        credentials: arn:aws:iam::214792946631:role/apigateway_invoke_lambda
        httpMethod: POST
        uri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:214792946631:function:apigw-large-file-handler-us-east-1-prod/invocations
        responses:
          default:
            statusCode: '200'
        requestParameters: {}
        passthroughBehavior: when_no_match
        contentHandling: CONVERT_TO_TEXT
        type: aws_proxy
  /asset-upload-batches/{id}:
    get:
      tags:
      - Asset Upload Batches
      operationId: EBS AM Get Upload Asset Batch
      summary: Get Upload Asset Batch
      description: Retrieve the specified upload asset batch within an organization.
      parameters:
      - description: The organization ID
        in: header
        name: X-EB-Organization-Id
        required: true
        schema:
          $ref: '#/components/schemas/organizationId'
      - description: Asset upload batch id.
        in: path
        name: id
        required: true
        schema:
          type: string
      - description: Source protocol type. Can be of API, SFTP or WEB
        in: query
        name: source
        required: true
        schema:
          type: string
          enum:
          - API
          - SFTP
          - WEB
          default: API
      - description: Upload action type. Can be one of UPDATE, REPLACE or DELETE
        in: query
        name: uploadType
        required: true
        schema:
          type: string
          enum:
          - UPDATE
          - REPLACE
          - DELETE
          default: UPDATE
      - description: Name of Asset Type
        in: query
        name: assetTypeName
        required: true
        schema:
          type: string
      - description: Available on manager portal (Settings --> Organization --> Contacts/Assets --> Assert Types)
        in: query
        name: assetTypeId
        required: false
        schema:
          type: string
          example: 665ff8e1a1b61d39e577b9c6
          default: 665ff8e1a1b61d39e577b9c6
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadBatchAssetResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    id: 68076691610b4b5869d240a5
                    organizationId: 1536984111644674
                    createdId: 1530249602924608
                    createdName: Nandish Siddaiah
                    lastModifiedId: 1530249602924608
                    lastModifiedName: Nandish Siddaiah
                    createdTimestamp: 1745315473046
                    lastModifiedTimestamp: 1745315478260
                    originalFileName: For API Gateway___91ae67a7-4390-455b-b505-858333558edd.csv
                    fileSuffix: .csv
                    storedFilePath: 1536984111644674/68076691610b4b5869d240a5/68076691610b4b5869d240a5.csv
                    fileSize: 918
                    contentType: text/csv
                    type: ASSET
                    uploadStatus: GEOCODING
                    uploadType: UPDATE
                    source: API
                    assetTypeId: 665ff8e1a1b61d39e577b9c6
                    assetTypeName: Buildings
                    totalRecordNum: 5
                    successNum: 5
                    withErrorNum: 0
                    criticalNum: 0
                    geocodingSuccessNum: 0
                    geocodingFailureNum: 0
                    geocodingTotalNum: 0
                    csvDelimiter: COMMA
          description: OK
        '400':
          content:
            text/plain:
              schema:
                oneOf:
                - type: string
                - type: object
              examples:
                Invalid Org ID:
                  summary: Invalid Org ID
                  value: 'BadRequest due to Not Found DataCenterId, orgId: 15369841116446741'
          description: OK
        '401':
          content:
            application/json:
              schema: {}
              examples:
                No X-EB-Organization-Id Header:
                  summary: Missing X-EB-Organization-Id Header
                  value: {}
          description: OK
      security:
      - API_Authorizer: []
      - BasicAuth: []
      - api_key: []
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: GET
        uri: https://ebs-restapi-prod-us.evbg.io/rest/v2/asset-management/asset-upload-batches/{id}
        responses:
          default:
            statusCode: '200'
        requestParameters:
          integration.request.path.id: method.request.path.id
          integration.request.header.Authorization: context.authorizer.override_token
        passthroughBehavior: when_no_match
  /asset-upload-batches/cancel/{id}:
    put:
      tags:
      - Asset Upload Batches
      operationId: EBS AM Update Upload Asset Batch
      summary: Update Upload Asset Batch
      description: Cancel an uploaded Batch process within an organization.
      parameters:
      - description: The organization ID
        in: header
        name: X-EB-Organization-Id
        required: true
        schema:
          $ref: '#/components/schemas/organizationId'
      - description: Asset batch id.
        in: path
        name: id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadBatchAssetResponse'
              examples:
                Success:
                  summary: Success
                  value:
                    id: 68076ebd610b4b5869d240a7
                    organizationId: 1536984111644674
                    createdId: 1530249602924608
                    createdName: Nandish Siddaiah
                    lastModifiedId: 1530249602924608
                    lastModifiedName: Nandish Siddaiah
                    createdTimestamp: 1745317565369
                    lastModifiedTimestamp: 1745317565514
                    originalFileName: For API Gateway___91ae67a7-4390-455b-b505-858333558edd.csv
                    fileSuffix: .csv
                    storedFilePath: 1536984111644674/68076ebd610b4b5869d240a7/68076ebd610b4b5869d240a7.csv
                    fileSize: 918
                    contentType: text/csv
                    type: ASSET
                    uploadStatus: PENDING
                    uploadType: UPDATE
                    source: API
                    assetTypeId: 665856825d59930bc2151633
                    assetTypeName: For API Gateway
                    totalRecordNum: 0
                    successNum: 0
                    withErrorNum: 0
                    criticalNum: 0
                    geocodingSuccessNum: 0
                    geocodingFailureNum: 0
                    geocodingTotalNum: 0
                    csvDelimiter: COMMA
          description: OK
        '400':
          content:
            text/plain:
              schema:
                oneOf:
                - type: string
                - type: object
              examples:
                Invalid Org ID:
                  summary: Invalid Org ID
                  value: 'BadRequest due to Not Found DataCenterId, orgId: 15369841116446741'
                Invalid Batch ID:
                  summary: Invalid Batch ID
                  value:
                    status: 400
                    errors:
                    - field: batchId
                      code: 70010
                      message: Upload BatchId not found
                Upload completed ot cancelled:
                  summary: Upload completed ot cancelled
                  value:
                    status: 400
                    errors:
                    - field: batchId
                      code: 70011
                      message: Upload Batch already completed or cancelled
          description: OK
        '401':
          content:
            application/json:
              schema: {}
              examples:
                No X-EB-Organization-Id Header:
                  summary: Missing X-EB-Organization-Id Header
                  value: {}
          description: OK
      security:
      - API_Authorizer: []
      - BasicAuth: []
      - api_key: []
      x-amazon-apigateway-integration:
        type: http_proxy
        httpMethod: PUT
        uri: https://ebs-restapi-prod-us.evbg.io/rest/v2/asset-management/asset-upload-batches/cancel/{id}
        responses:
          default:
            statusCode: '200'
        requestParameters:
          integration.request.path.id: method.request.path.id
          integration.request.header.Authorization: context.authorizer.override_token
        passthroughBehavior: when_no_match
components:
  schemas:
    UploadBatchAssetResponse:
      type: object
      properties:
        id:
          type: string
        organizationId:
          type: number
        createdId:
          type: number
        createdName:
          type: string
        lastModifiedId:
          type: number
        lastModifiedName:
          type: string
        createdTimestamp:
          type: number
        lastModifiedTimestamp:
          type: number
        originalFileName:
          type: string
        fileSuffix:
          type: string
        storedFilePath:
          type: string
        fileSize:
          type: number
        contentType:
          type: string
        type:
          type: string
        uploadStatus:
          type: string
        uploadType:
          type: string
        source:
          type: string
        assetTypeId:
          type: string
        assetTypeName:
          type: string
        totalRecordNum:
          type: number
        successNum:
          type: number
        withErrorNum:
          type: number
        criticalNum:
          type: number
        geocodingSuccessNum:
          type: number
        geocodingFailureNum:
          type: number
        geocodingTotalNum:
          type: number
        csvDelimiter:
          type: string
    ListUploadBatchResponse:
      type: object
      properties:
        pageSize:
          type: number
        start:
          type: number
        totalCount:
          type: number
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              organizationId:
                type: number
              createdId:
                type: number
              createdName:
                type: string
              lastModifiedId:
                type: number
              lastModifiedName:
                type: string
              createdTimestamp:
                type: number
              lastModifiedTimestamp:
                type: number
              originalFileName:
                type: string
              fileSuffix:
                type: string
              storedFilePath:
                type: string
              fileSize:
                type: number
              contentType:
                type: string
              type:
                type: string
              uploadStatus:
                type: string
              uploadType:
                type: string
              source:
                type: string
              assetTypeId:
                type: string
              assetTypeName:
                type: string
              totalRecordNum:
                type: number
              successNum:
                type: number
              withErrorNum:
                type: number
              criticalNum:
                type: number
              geocodingSuccessNum:
                type: number
              geocodingFailureNum:
                type: number
              geocodingTotalNum:
                type: number
              csvDelimiter:
                type: string
        currentPageNo:
          type: number
        totalPageCount:
          type: number
    organizationId:
      description: Everbridge Organization id.  Available on manager portal (Settings --> Organization --> Base Information)
      maxLength: 16
      type: integer
      example: '1536984111644674'
      default: '1536984111644674'
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      description: Basic Authentication Token
    API_Authorizer:
      type: apiKey
      name: Authorization
      description: oAuth Token
      in: header
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        authorizerUri: arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:214792946631:function:API_Authorizer_us-east-1_prod:live/invocations
        authorizerCredentials: arn:aws:iam::214792946631:role/asset-management-prod-us-us-east-1-0-us-east-1-gw
        authorizerResultTtlInSeconds: 300
        identitySource: method.request.header.Authorization,method.request.header.PathCacheKey,method.request.header.MethodCacheKey
        type: request
    api_key:
      type: apiKey
      name: x-api-key
      description: API Key - For System Use
      in: header
x-readme:
  explorer-enabled: true
  proxy-enabled: true
